### ISSUE TITLE
⬆️ Migrate to the Latest Workspace Version

### ISSUE THREAD

**Issue by usamazansari** [usamazansari/itinerary-assistant#153]
## Migrate to `nx@13.8.1`

Adapt to the changes brought by `Nx` in major version `13.x`

- [x] `apps/api`
- [x] `apps/ui`
- [x] `tailwind`
- [x] `apps/ui-e2e`
- [x] `libs/api/core`
- [x] `libs/api/database/entities`
- [x] `libs/api/database/typeorm`
- [x] `libs/api/features/trip`
- [x] `libs/shared/data`
- [x] `libs/shared/styles`
- [x] `libs/ui/core`
- [x] `libs/ui/design/layout`
- [x] `libs/ui/design/components`
- [x] `libs/ui/design/icons`
- [x] `libs/ui/design/material`
- [x] `libs/ui/features/trip`

**Comment by usama251993** [comment]
Closed in #154

**Comment by usamazansari** [comment]
Faulty Migration in #154

**Comment by usama251993** [comment]
Closed in #157
