### ISSUE TITLE
👽 Implement API to fetch User Details

### ISSUE THREAD

**Issue by usama251993** [usamazansari/itinerary-assistant#159]
## User Details API Endpoints

- [ ] `getUser(id: string): APIEndpointResponse<User>`
- [ ] `createUser(payload: User): APIEndpointResponse<{ operationStatus: boolean }>`
- [ ] `updateUser(payload: Partial<User>): APIEndpointResponse<{ operationStatus: boolean }>`
- [ ] `deleteUser(id: string): APIEndpointResponse<{ operationStatus: boolean }>`

**Comment by usamazansari** [comment]
Irrelevant Issue since GraphQL is now in place
