### ISSUE TITLE
🌱 Seed Database

### ISSUE THREAD

**Issue by usama251993** [usamazansari/itinerary-assistant#161]
## Database Seed

Seed the database with User Information

- [x] #193 
- [x] #194
- [x] Update the files inside `libs\api\database\seed\src\lib\seeds`

**Comment by usamazansari** [comment]
On Hold

**Comment by usamazansari** [comment]
Closed by #167

**Comment by usamazansari** [comment]
Reopened for `Neo4j` Database

**Comment by usama251993** [comment]
Closed by #219
