### ISSUE TITLE
🗃️ CRUD for Social Connections Entity

### ISSUE THREAD

**Issue by usamazansari** [usamazansari/itinerary-assistant#207]
## SocialConnection Entity CRUD

- [x] `createSocialConnection(socialConnection: SocialConnection)`
- [x] `getSocialConnection(id: string)`
- [x] `updateSocialConnection(id: string, socialConnection: Partial<SocialConnection>)`
- [x] `deleteSocialConnection(id: string)`
- [x] `associateSocialConnectionWithPerson(socialConnectionId: string, personId: string)`

**Comment by usama251993** [comment]
Closed by #214
