### ISSUE TITLE
⏪ Reset `Nx` Workspace

### ISSUE THREAD

**Issue by usamazansari** [usamazansari/itinerary-assistant#225]
## Workspace Reset

> Due to Migration to `nx@14`

- [x] Remove all the libraries
- [ ] Share an abstract class between frontend and the backend
- [x] Use `GraphQL` to fetch data end to end from `Neo4j` database

**Comment by usamazansari** [comment]
Could not share an abstract class between Angular and NestJS, the compilation could not resolve all the modules

**Comment by usama251993** [comment]
Fixed by #226
