### ISSUE TITLE
📑 User Details

### ISSUE THREAD

**Issue by usama251993** [usamazansari/itinerary-assistant#33]
### Implement User Details in the Sidenav
Reference - [material.io](https://lh3.googleusercontent.com/tVfI-EewJiKQqYvmcV8xkY2AIh_GXLSDlh5nzGka0SooqiJey_MWjtdpETNpBj8GEIzbE4LlaDIRX90ibVJlchUKKQ8qanhrRgFE=w1064-v0)

- [x] #158
- [x] #159
- [ ] Implement the UI Design for User Page

**Comment by usamazansari** [comment]
Irrelevant Issue
